### PR TITLE
Added support for Asm labels

### PR DESCRIPTION
**Pull request by t11230**
- Fixed superclass for ArrayDeclExt
- Added some spaces for readability to _generate_type
- Moved templated rules into _AsmAndAttributesMixin

### CODE REVIEW

**Comment by t11230** [comment]
This should resolve #33

**Comment by inducer** [comment]
This has some conflicts now. Could you resolve those?

**Comment by inducer** [comment]
Thanks for working on this! Changes LGTM. Ready to go in once the conflicts are resolved.

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
