### PR TITLE
Make pycparserext work with pycparser >= 2.18.

### PR DESCRIPTION
**Pull request by manueljacob**

### CODE REVIEW

**Comment by inducer** [comment]
Thanks!

**Comment by inducer** [comment]
CI passed, too.

**Comment by inducer** [comment]
Btw, did you need that rolled into a new release?

**Comment by manueljacob** [comment]
In the moment I've `pip install --editable .`ed it anyway because of more (local) changes. Probably a release makes more sense after I've upstreamed these features.

**Comment by inducer** [comment]
Sounds good. Just let me know.

**Pull request merged**
